import { useState, useRef, useEffect, useCallback } from 'react'
import { toPng } from 'html-to-image'
import JSZip from 'jszip'
import { saveAs } from 'file-saver'
import { useAnalysisContext } from '../context/AnalysisContext'

// ---------------------------------------------------------------------------
// Markdown generators
// ---------------------------------------------------------------------------

function buildRepoName(result) {
  if (result.owner && result.repo) return `${result.owner}/${result.repo}`
  return 'Unknown Repository'
}

function buildFullReport(result) {
  const repoName = buildRepoName(result)
  const date = new Date().toISOString().split('T')[0]
  const fileCount = result.file_count || '?'

  const lines = [
    `# FossilAI Analysis Report: ${repoName}`,
    '',
    `**Generated:** ${date}`,
    `**Files analyzed:** ${fileCount}`,
    `**Source:** https://github.com/${repoName}`,
    '',
    '---',
    '',
  ]

  // Architecture
  if (result.architecture) {
    lines.push('## Architecture', '', result.architecture, '', '---', '')
  }

  // Modules
  if (result.modules) {
    lines.push('## Modules', '', result.modules, '', '---', '')
  }

  // ADRs
  const adrs = result.adrs || []
  if (adrs.length > 0) {
    lines.push('## Architectural Decision Records', '')
    adrs.forEach((adr, i) => {
      lines.push(`### ADR ${i + 1}: ${adr.title}`, '')
      lines.push(`- **Status:** ${adr.status}`)
      if (adr.context) lines.push(`- **Context:** ${adr.context}`)
      lines.push(`- **Decision:** ${adr.decision}`)
      if (adr.consequences) lines.push(`- **Consequences:** ${adr.consequences}`)
      lines.push('')
    })
    lines.push('---', '')
  }

  // Tech Debt
  const techDebt = result.tech_debt || []
  if (techDebt.length > 0) {
    lines.push('## Tech Debt', '')
    lines.push('| File | Type | Severity | Description | Suggested Fix |')
    lines.push('|------|------|----------|-------------|---------------|')
    techDebt.forEach((item) => {
      const file = item.file || ''
      const type = (item.type || '').replace(/_/g, ' ')
      const severity = item.severity || ''
      const desc = (item.description || '').replace(/\|/g, '\\|').replace(/\n/g, ' ')
      const fix = (item.suggested_fix || '').replace(/\|/g, '\\|').replace(/\n/g, ' ')
      lines.push(`| ${file} | ${type} | ${severity} | ${desc} | ${fix} |`)
    })
    lines.push('', '---', '')
  }

  // Refactoring Opportunities
  const refactors = result.refactor_scenarios || []
  if (refactors.length > 0) {
    lines.push('## Refactoring Opportunities', '')
    refactors.forEach((r, i) => {
      lines.push(`### ${i + 1}. ${r.title}`, '')
      if (r.description) lines.push(r.description, '')
      if (r.target_files && r.target_files.length > 0) {
        lines.push(`**Target files:** ${r.target_files.join(', ')}`)
      }
      if (r.impact) lines.push(`**Expected impact:** ${r.impact}`)
      lines.push('')
    })
    lines.push('---', '')
  }

  // Warnings
  const warnings = result.warnings || []
  if (warnings.length > 0) {
    lines.push('## Warnings', '')
    warnings.forEach((w) => lines.push(`- ${w}`))
    lines.push('')
  }

  lines.push('---', '', '*Generated by FossilAI — AI Code Archaeologist*', '')
  return lines.join('\n')
}

function buildSingleADR(adr, index) {
  const lines = [
    `# ADR ${index + 1}: ${adr.title}`,
    '',
    `**Status:** ${adr.status}`,
    '',
    '## Context',
    '',
    adr.context || 'No context provided.',
    '',
    '## Decision',
    '',
    adr.decision || 'No decision recorded.',
    '',
    '## Consequences',
    '',
    adr.consequences || 'No consequences recorded.',
    '',
    '---',
    '*Generated by FossilAI*',
    '',
  ]
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// PNG capture helper
// ---------------------------------------------------------------------------

const IMAGE_WIDTH = 2048
const IMAGE_HEIGHT = 1536

async function captureGraphPng() {
  const viewport = document.querySelector('.react-flow__viewport')
  if (!viewport) return null

  try {
    const dataUrl = await toPng(viewport, {
      backgroundColor: '#0f0f14',
      width: IMAGE_WIDTH,
      height: IMAGE_HEIGHT,
      style: {
        width: `${IMAGE_WIDTH}px`,
        height: `${IMAGE_HEIGHT}px`,
        transform: viewport.style.transform,
      },
    })
    return dataUrl
  } catch {
    return null
  }
}

function dataUrlToBlob(dataUrl) {
  const [meta, base64] = dataUrl.split(',')
  const mime = meta.match(/:(.*?);/)[1]
  const bytes = atob(base64)
  const arr = new Uint8Array(bytes.length)
  for (let i = 0; i < bytes.length; i++) {
    arr[i] = bytes.charCodeAt(i)
  }
  return new Blob([arr], { type: mime })
}

// ---------------------------------------------------------------------------
// Filename sanitizer
// ---------------------------------------------------------------------------

function sanitizeFilename(name) {
  return name.replace(/[^a-zA-Z0-9_-]/g, '_').toLowerCase()
}

// ---------------------------------------------------------------------------
// ExportButton component
// ---------------------------------------------------------------------------

export default function ExportButton() {
  const { state, showToast } = useAnalysisContext()
  const [open, setOpen] = useState(false)
  const [exporting, setExporting] = useState(null) // null | 'markdown' | 'png' | 'adrs' | 'all'
  const dropdownRef = useRef(null)

  const result = state.analysisResult
  const isDisabled = !result || state.status !== 'loaded'

  // Close dropdown on outside click
  useEffect(() => {
    function handleClick(e) {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target)) {
        setOpen(false)
      }
    }
    if (open) {
      document.addEventListener('mousedown', handleClick)
      return () => document.removeEventListener('mousedown', handleClick)
    }
  }, [open])

  const repoName = result ? buildRepoName(result) : ''
  const safeRepoName = sanitizeFilename(repoName)

  // -----------------------------------------------------------------------
  // Export handlers
  // -----------------------------------------------------------------------

  const handleExportMarkdown = useCallback(async () => {
    if (!result) return
    setExporting('markdown')
    setOpen(false)

    try {
      const markdown = buildFullReport(result)
      const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' })
      saveAs(blob, `fossilai-${safeRepoName}-report.md`)
      showToast('Markdown report exported')
    } finally {
      setExporting(null)
    }
  }, [result, safeRepoName, showToast])

  const handleExportPng = useCallback(async () => {
    if (!result) return
    setExporting('png')
    setOpen(false)

    try {
      const dataUrl = await captureGraphPng()
      if (dataUrl) {
        const blob = dataUrlToBlob(dataUrl)
        saveAs(blob, `fossilai-${safeRepoName}-graph.png`)
        showToast('Graph exported as PNG')
      } else {
        showToast('Could not capture graph', 'error')
      }
    } finally {
      setExporting(null)
    }
  }, [result, safeRepoName, showToast])

  const handleExportADRs = useCallback(async () => {
    if (!result) return
    const adrs = result.adrs || []
    if (adrs.length === 0) return

    setExporting('adrs')
    setOpen(false)

    try {
      const zip = new JSZip()
      const folder = zip.folder('adrs')
      adrs.forEach((adr, i) => {
        const filename = `adr-${String(i + 1).padStart(3, '0')}-${sanitizeFilename(adr.title)}.md`
        folder.file(filename, buildSingleADR(adr, i))
      })

      const blob = await zip.generateAsync({ type: 'blob' })
      saveAs(blob, `fossilai-${safeRepoName}-adrs.zip`)
      showToast(`${adrs.length} ADRs exported`)
    } finally {
      setExporting(null)
    }
  }, [result, safeRepoName, showToast])

  const handleExportAll = useCallback(async () => {
    if (!result) return
    setExporting('all')
    setOpen(false)

    try {
      const zip = new JSZip()

      // Full report
      zip.file('report.md', buildFullReport(result))

      // Individual ADRs
      const adrs = result.adrs || []
      if (adrs.length > 0) {
        const adrFolder = zip.folder('adrs')
        adrs.forEach((adr, i) => {
          const filename = `adr-${String(i + 1).padStart(3, '0')}-${sanitizeFilename(adr.title)}.md`
          adrFolder.file(filename, buildSingleADR(adr, i))
        })
      }

      // Graph PNG
      const dataUrl = await captureGraphPng()
      if (dataUrl) {
        const [, base64] = dataUrl.split(',')
        zip.file('dependency-graph.png', base64, { base64: true })
      }

      // Raw analysis JSON
      zip.file('analysis.json', JSON.stringify(result, null, 2))

      const blob = await zip.generateAsync({ type: 'blob' })
      saveAs(blob, `fossilai-${safeRepoName}-export.zip`)
      showToast('Full export downloaded')
    } finally {
      setExporting(null)
    }
  }, [result, safeRepoName, showToast])

  // -----------------------------------------------------------------------
  // Menu items
  // -----------------------------------------------------------------------

  const menuItems = [
    {
      id: 'markdown',
      label: 'Export as Markdown',
      sublabel: 'Full analysis report (.md)',
      icon: (
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
      ),
      handler: handleExportMarkdown,
      disabled: false,
    },
    {
      id: 'png',
      label: 'Export Graph as PNG',
      sublabel: 'Dependency graph image',
      icon: (
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
      ),
      handler: handleExportPng,
      disabled: false,
    },
    {
      id: 'adrs',
      label: 'Export ADRs',
      sublabel: `${result?.adrs?.length || 0} decision records (.zip)`,
      icon: (
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
        </svg>
      ),
      handler: handleExportADRs,
      disabled: !result?.adrs?.length,
    },
    {
      id: 'all',
      label: 'Download All (.zip)',
      sublabel: 'Report + graph + ADRs + JSON',
      icon: (
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
      ),
      handler: handleExportAll,
      disabled: false,
    },
  ]

  return (
    <div className="relative" ref={dropdownRef}>
      {/* Trigger button */}
      <button
        onClick={() => !isDisabled && setOpen((v) => !v)}
        disabled={isDisabled}
        className={`flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium transition-colors ${
          isDisabled
            ? 'bg-fossil-200 dark:bg-fossil-700 text-fossil-400 dark:text-fossil-500 cursor-not-allowed'
            : 'bg-accent/10 hover:bg-accent/20 text-accent'
        }`}
      >
        {exporting ? (
          <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
          </svg>
        ) : (
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
        )}
        <span className="hidden sm:inline">Export</span>
        {!exporting && (
          <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        )}
      </button>

      {/* Dropdown menu */}
      {open && !isDisabled && (
        <div className="absolute right-0 top-full mt-1 w-64 bg-white dark:bg-fossil-800 border border-fossil-200 dark:border-fossil-700 rounded-lg shadow-lg z-50 py-1 overflow-hidden">
          {menuItems.map((item) => (
            <button
              key={item.id}
              onClick={item.handler}
              disabled={item.disabled || !!exporting}
              className={`w-full flex items-start gap-3 px-3 py-2.5 text-left transition-colors ${
                item.disabled || exporting
                  ? 'text-fossil-400 dark:text-fossil-500 cursor-not-allowed'
                  : 'text-fossil-700 dark:text-fossil-300 hover:bg-fossil-100 dark:hover:bg-fossil-700'
              }`}
            >
              <span className="flex-shrink-0 mt-0.5">{item.icon}</span>
              <div className="min-w-0">
                <p className="text-xs font-medium">{item.label}</p>
                <p className="text-[10px] text-fossil-400 dark:text-fossil-500">{item.sublabel}</p>
              </div>
              {exporting === item.id && (
                <svg className="w-3.5 h-3.5 animate-spin flex-shrink-0 mt-0.5 text-accent" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                </svg>
              )}
            </button>
          ))}
        </div>
      )}
    </div>
  )
}
